once, there was a crow who was very thirsty and tired. he saw a water jug and was very happy as he thought there would
be a lot of water. unfortunately, when he peeked in, the crow saw that there was very less water and he 
would not be able to reach it. so, he started..... 